### ISSUE TITLE
FileNotFoundException when loading the mod

### ISSUE THREAD

**Issue by FPSUsername** [MrCrayfish/GlassCutter#8]
`FileNotFoundException` when loading the mod on a Forge server with Forge build 1.15.2-31.1.47

This also happens with the [GoldenHopper](https://github.com/MrCrayfish/GoldenHopper) and [Venture](https://github.com/MrCrayfish/Venture) mods.

```prolog
[22Apr2020 16:00:37.622] [Forge Version Check/WARN] [net.minecraftforge.fml.VersionChecker/]: Failed to process update information
java.io.FileNotFoundException: https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/glasscutter/update.json
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_241]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_241]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945) ~[?:1.8.0_241]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_241]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_241]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:189) ~[?:?]
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:206) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_241]
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:157) [?:?]
Caused by: java.io.FileNotFoundException: https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/glasscutter/update.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896) ~[?:1.8.0_241]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_241]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_241]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[?:1.8.0_241]
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:173) ~[?:?]
	... 3 more
```

**Comment by MrCrayfish** [comment]
This should be resolved now.
